cache:
  yarn: true
language: node_js
node_js:
  - 8.9.4
install:
  - yarn global add codecov
script:
  - yarn install
  - NODE_ENV=test yarn test
  - NODE_ENV=production yarn build
  - NODE_ENV=production yarn export
  - touch out/.nojekyll
  - codecov
deploy:
  provider: pages
  local-dir: out
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
