cache:
  yarn: true
language: node_js
node_js:
  - 8.9.4
env:
  global:
    NODE_ENV=production
script:
  - yarn install
  - yarn build
  - yarn export
  - touch out/.nojekyll
deploy:
  provider: pages
  local-dir: out
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
